FROM        eclipse-temurin:17-jre

ENV         DEBIAN_FRONTEND=noninteractive

RUN         apt-get update -y \
            && apt-get install -y ca-certificates curl dos2unix fontconfig git iproute2 jq libfreetype6 libstdc++6 openssl sqlite3 tar tzdata unzip wget zip
