# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
      day: "monday"
  - package-ecosystem: docker
    directory: /java/8
    schedule:
      interval: "weekly"
      day: "monday"
  - package-ecosystem: docker
    directory: /java/11
    schedule:
      interval: "weekly"
      day: "monday"
  - package-ecosystem: docker
    directory: /java/17
    schedule:
      interval: "weekly"
      day: "monday"
  - package-ecosystem: docker
    directory: /oses/alpine
    schedule:
      interval: "weekly"
      day: "monday"
  - package-ecosystem: docker
    directory: /oses/ubuntu
    schedule:
      interval: "weekly"
      day: "monday"