name: build java installers
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - main
    paths:
      - java-installers/**
jobs:
  push:
    name: "images:java-installer-${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 8
          - 11
          - 17
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./java-installers
          file: ./java-installers/${{ matrix.tag }}/Dockerfile
          push: true
          tags: |
            ghcr.io/kpatino/images:java-installer${{ matrix.tag }}
